module.exports = {
  ar: {
    chooseLang: "🌐 اختر اللغة\n\nمرحبًا بك في مقرأة الإمام الجزري.\nمن فضلك اختر لغة التعامل:",
    langSaved: "✅ تم حفظ لغتك: العربية",
    anyTextWelcome: "🌿 أهلاً بك في مقرأة الإمام الجزري.\n\nاستخدم الأزرار الموجودة في القائمة للوصول إلى الخدمات 👇",
    errorMessage: "⚠️ حدث خطأ مؤقت. حاول مرة أخرى بعد قليل.",
    welcome: `السلام عليكم ورحمة الله وبركاته 🌿\n\nأهلاً وسهلاً بك في\n\n📖 <b>مقرأة الإمام الجزري للإقراء والإجازة بالسند</b>\n\nمرحبًا بك يا {name} 🌹\n\nنحن نسعى لخدمة كتاب الله تعالى من خلال التعليم المنهجي، والتصحيح، والحفظ، والإقراء والإجازة بالسند.\n\nاختر الخدمة التي تريدها من القائمة أدناه 👇`,
    homeWelcome: `📖 <b>مقرأة الإمام الجزري</b>\n\nأهلاً بك من جديد 🌿\n\nاختر الخدمة التي تريدها:`,
    btnPrograms: "📚 البرامج التعليمية",
    btnTeachers: "👨‍🏫 الشيوخ",
    btnBalance: "⏱️ رصيد الدقائق",
    btnBuy: "💳 شراء دقائق",
    btnBooking: "📅 حجز جلسة",
    btnAccount: "👤 حسابي",
    btnCertificates: "📜 الإجازات والشهادات",
    btnBooks: "📚 الكتب والمتون",
    btnAudio: "🎧 الصوتيات والمحاضرات",
    btnSupport: "📞 الدعم والمساعدة",
    btnHome: "🔙 الرئيسية",
    btnBack: "🔙 رجوع",
    btnChangeLang: "🌐 تغيير اللغة",
    btnRegister: "📝 التسجيل في المقرأة",
    btnMySchedule: "📅 جدولي الدراسي",
    btnMyCode: "🔖 كودي",
    regWelcome: `📝 <b>التسجيل في المقرأة</b>\n\nلتسجيلك في المقرأة، نحتاج بعض المعلومات.\n\nسنجمعها على خطوات قصيرة.\n\nهل أنت مستعد؟`,
    regStartBtn: "✅ نعم، لنبدأ",
    regCancelBtn: "❌ إلغاء التسجيل",
    regAskName: "1️⃣ <b>ما اسمك الكامل؟</b>\n\nأرسله كرسالة نصية.",
    regAskAge: "2️⃣ <b>كم عمرك؟</b>\n\nأرسل العمر بالأرقام فقط (مثال: 25).",
    regAskGender: "3️⃣ <b>ما جنسك؟</b>\n\nاختر:",
    regGenderMale: "👨 ذكر",
    regGenderFemale: "👩 أنثى",
    regAskLevel: "4️⃣ <b>ما مستواك في القراءة؟</b>\n\nاختر:",
    regLevel1: "🌱 مبتدئ",
    regLevel2: "📖 متوسط",
    regLevel3: "⭐ متقدم",
    regLevel4: "🎓 حافظ/مجيد",
    regAskPhone: "5️⃣ <b>ما رقم جوالك؟</b>\n\nأرسله مع رمز الدولة.\nمثال: +251912345678",
    regAskMemorizedWhat: "6️⃣ <b>ماذا حفظت من القرآن؟</b>\n\nاكتب ما حفظته (مثال: جزء عم، البقرة، لا شيء).",
    regAskMemorizedWhere: "7️⃣ <b>أين حفظت؟</b>\n\nاكتب المكان (مسجد، مركز، بيت).",
    regAskCenter: "8️⃣ <b>اسم المركز أو المسجد؟</b>\n\nإذا لم يكن هناك، أرسل: لا يوجد.",
    regAskTeacher: "9️⃣ <b>اسم المقرئ أو المجيز؟</b>\n\nإذا لم يكن هناك، أرسل: لا يوجد.",
    regAskDate: "🔟 <b>متى حفظت؟</b>\n\nمثال: 2020 أو رمضان 1441.",
    regAskSchedule: "📅 <b>اختر برنامجك الدراسي:</b>\n\n{details}",
    regScheduleMale: "للرجال: الثلاثاء، الأربعاء، الخميس",
    regScheduleFemale: "للنساء: السبت، الأحد، الاثنين",
    regAskPeriod: "⏰ <b>اختر الفترة:</b>",
    regPeriodMorning: "🌅 صباحية (9:00 - 11:00)",
    regPeriodAfternoon: "☀️ مسائية (2:00 - 3:30)",
    regPeriodNight: "🌙 ليلية (9:00 - 11:00)",
    regConfirm: `📋 <b>مراجعة بياناتك</b>\n\n👤 الاسم: {name}\n🎂 العمر: {age}\n⚥ الجنس: {gender}\n📖 المستوى: {level}\n📱 الجوال: {phone}\n\n📚 <b>بيانات الحفظ:</b>\n• ماذا حفظت: {memorized_what}\n• أين: {memorized_where}\n• المركز: {center}\n• المقرئ: {teacher}\n• التاريخ: {date}\n\n📅 <b>البرنامج:</b>\n• الأيام: {days}\n• الفترة: {period}\n\nهل تؤكد التسجيل؟`,
    regConfirmBtn: "✅ تأكيد التسجيل",
    regEditBtn: "✏️ تعديل",
    regDone: `✅ <b>تم تسجيلك بنجاح!</b>\n\n🔖 <b>كودك الشخصي:</b>\n<code>{code}</code>\n\n📅 تاريخ التسجيل: {date}\n\n📌 احتفظ بهذا الكود.\n\nسيتم مراجعة طلبك وإشعارك قريبًا.`,
    regCanceled: "❌ تم إلغاء التسجيل.",
    regAlreadyRegistered: `✅ أنت مسجل بالفعل.\n\n🔖 كودك: <code>{code}</code>`,
    regInvalidAge: "⚠️ أرسل عمرك بالأرقام فقط (10-100).",
    regInvalidPhone: "⚠️ أرسل رقمًا صحيحًا مع رمز الدولة.",
    programs: "📚 <b>البرامج التعليمية</b>\n\nاختر البرنامج:",
    progNorania: "📖 القاعدة النورانية",
    progNazr: "🕌 التلاوة والنظر",
    progHifz: "📕 الحفظ",
    progHafs: "🎓 حفص والإجازة",
    progSeven: "📚 القراءات السبع",
    progTen: "📚 القراءات العشر",
    noraniaTitle: "📖 <b>برنامج القاعدة النورانية</b>",
    noraniaBody: `برنامج تأسيسي للمبتدئين.\n\nيشمل:\n1️⃣ الحروف\n2️⃣ الحركات\n3️⃣ التنوين\n4️⃣ المدود\n5️⃣ السكون\n6️⃣ الشدة\n7️⃣ اللام الشمسية والقمرية\n8️⃣ الكلمات\n9️⃣ التدريب`,
    lessonsBtn: "📋 الدروس",
    bookSessionBtn: "📅 حجز جلسة",
    backPrograms: "🔙 البرامج",
    lessonsTitle: "📖 <b>دروس القاعدة النورانية</b>\n\nاختر الدرس:",
    lessonTitle: "📖 <b>الدرس {n}</b>",
    lessonBody: `يمكنك دراسة هذا الدرس مع أحد المقرئين.\n\n🎧 الاستماع\n📖 القراءة\n👨‍🏫 التصحيح`,
    bookWithTeacherBtn: "📅 حجز مع شيخ",
    backLessons: "🔙 الدروس",
    nazrTitle: "🕌 <b>برنامج التلاوة والنظر</b>",
    nazrBody: "برنامج لتصحيح القراءة وضبط المخارج.",
    hifzTitle: "📕 <b>برنامج الحفظ</b>",
    hifzBody: "برنامج تدريجي للحفظ والمراجعة.",
    hafsTitle: "🎓 <b>برنامج حفص والإجازة</b>",
    hafsBody: "مسار متكامل في رواية حفص مع الإجازة.",
    sevenTitle: "📚 <b>القراءات السبع</b>",
    sevenBody: "مسار متدرج للقراءات السبع.",
    tenTitle: "📚 <b>القراءات العشر</b>",
    tenBody: "برنامج متخصص في القراءات العشر.",
    chooseTeacherBtn: "👨‍🏫 اختيار الشيخ",
    teachers: "👨‍🏫 <b>الشيوخ والمقرئون</b>\n\nاختر المقرئ:",
    teacherAbuZaid: "🟢 المقرئ أبو زيد خالد أحمد الولادي",
    salafiScholarsBtn: "📚 شيوخ السلفية",
    otherTeachers: "👨‍🏫 مقرئون آخرون",
    teacherAbuZaidTitle: "👨‍🏫 <b>المقرئ أبو زيد خالد أحمد الولادي</b>",
    teacherAbuZaidBody: `🟢 متاح للتدريس\n\n📖 التخصصات:\n• التلاوة والتصحيح\n• التجويد\n• رواية حفص\n• الحفظ\n• الإجازة بالسند\n• القراءات\n\n📅 <b>جدوله:</b>\n{schedule}`,
    backTeachers: "🔙 الشيوخ",
    salafiTitle: "📚 <b>شيوخ السلفية</b>\n\nاختر الشيخ:",
    salafiBody: `📖 <b>{name}</b>\n\n{description}\n\n🔗 اضغط للفتح:`,
    openChannelBtn: "▶️ فتح القناة",
    openPlaylistBtn: "📺 قوائم التشغيل",
    backSalafi: "🔙 شيوخ السلفية",
    booksTitle: "📚 <b>المتون والكتب</b>\n\nاختر المتن:",
    downloadBtn: "⬇️ تحميل PDF",
    watchExplanationBtn: "▶️ مشاهدة الشرح",
    backBooks: "🔙 المتون",
    explanationTitle: "▶️ <b>{title}</b>\n\nقائمة تشغيل كاملة ({count} حلقة)\n\nاضغط الزر:",
    audioTitle: "🎧 <b>الصوتيات والمحاضرات</b>\n\nاختر المحاضرة:",
    audioBody: `🎙️ <b>{title}</b>\n\nاضغط الزر للمشاهدة:`,
    watchNowBtn: "▶️ مشاهدة الآن",
    backAudio: "🔙 الصوتيات",
    balanceTitle: "⏱️ <b>رصيد الدقائق</b>",
    balanceBody: `👤 {name}\n\n━━━━━━━━━━━━\n\n⏱️ المتبقي: <b>{minutes} دقيقة</b>\n💰 القيمة: <b>{value} ETB</b>\n\n💡 1 دقيقة = 5 ETB`,
    historyBtn: "📊 سجل الدقائق",
    historyTitle: "📊 <b>سجل الدقائق</b>",
    historyEmpty: "لا توجد عمليات.",
    backBalance: "🔙 الرصيد",
    buyTitle: "💳 <b>شراء الدقائق</b>",
    buyBody: "سعر الدقيقة: 5 ETB\n\nاختر الباقة:",
    confirmPackTitle: "💳 <b>تأكيد الباقة</b>",
    confirmPackBody: `⏱️ الدقائق: {minutes}\n💰 السعر: {price} ETB\n\nبعد الدفع أرسل الإيصال للإدارة.`,
    wantBuyBtn: "💰 شراء الباقة",
    backPackages: "🔙 الباقات",
    purchaseRequested: `✅ <b>تم تسجيل طلب الشحن</b>\n\n📌 أرسل صورة الإيصال الآن.\n\n🔐 سيتم الاعتماد بعد المراجعة.`,
    sendReceiptNow: "📷 أرسل صورة الإيصال",
    receiptReceived: `✅ <b>تم استلام إيصالك</b>\n\nسيتم مراجعته قريبًا.\n\nشكرًا لك 🌹`,
    rechargeApproved: `🎉 <b>تم اعتماد شحنك</b>\n\n⏱️ الدقائق: {minutes}\n💰 المبلغ: {price} ETB\n\n⏱️ رصيدك الجديد: {total} دقيقة`,
    rechargeRejected: `❌ <b>تم رفض الشحن</b>\n\n{reason}`,
    bookingTitle: "📅 <b>حجز جلسة</b>",
    bookingBody: "رصيدك: ⏱️ {minutes} دقيقة\n\nاختر المدة:",
    noBalanceWarning: "⚠️ <b>لا يوجد رصيد كافٍ.</b>",
    noBalanceBody: "رصيدك: {minutes} دقيقة\n\nللحجز يجب أن يكون لديك رصيد.",
    min15: "15 دقيقة", min20: "20 دقيقة", min30: "30 دقيقة",
    min45: "45 دقيقة", min60: "60 دقيقة",
    notEnoughBalance: "❌ لا يكفي رصيدك.\n\nرصيدك: {minutes}\nالمطلوب: {requested}",
    chooseSessionTime: "📅 <b>اختيار الموعد</b>",
    chooseSessionTimeBody: "المدة: {minutes} دقيقة\n\nاختر الفترة:",
    morning: "🌅 صباحًا", afternoon: "☀️ بعد الظهر", night: "🌙 مساءً",
    backBooking: "🔙 الحجز",
    bookingRequestTitle: "📅 <b>طلب حجز</b>",
    bookingRequestBody: `👨‍🏫 أبو زيد خالد\n⏱️ {minutes} دقيقة\n🕐 {period}\n\nهل ترسل الطلب؟`,
    sendBookingBtn: "✅ إرسال الطلب",
    cancelBtn: "❌ إلغاء",
    bookingConfirmedTitle: "✅ <b>تم إرسال الطلب</b>",
    bookingConfirmedBody: `⏱️ المدة: {minutes}\n💳 محجوز: {minutes}\n⏱️ المتبقي: {remaining}\n\n📌 سيتم إشعارك عند الاعتماد.`,
    myBalanceBtn: "⏱️ رصيدي",
    notEnoughShort: "❌ الرصيد غير كافٍ.",
    accountTitle: "👤 <b>حسابي</b>",
    accountBody: `الاسم: {name}\n🔖 الكود: <code>{code}</code>\n🎂 العمر: {age}\n⚥ الجنس: {gender}\n📖 المستوى: {level}\n📱 الجوال: {phone}\n\n⏱️ الرصيد: {minutes}\n📚 البرنامج: {program}\n📅 الأيام: {days}\n⏰ الفترة: {period}\n\n📌 التسجيل: {reg_date}`,
    notSet: "غير محدد",
    noProgram: "لم يتم اختيار برنامج",
    chooseProgramBtn: "📚 اختيار برنامج",
    historyShortBtn: "📊 السجل",
    notRegistered: "⚠️ أنت غير مسجل.\n\nاضغط زر التسجيل.",
    certificatesTitle: "📜 <b>الإجازات والشهادات</b>",
    certificatesBody: `بعد إكمال المتطلبات:\n\n🎓 شهادة إتمام\n📜 شهادة حفظ\n📖 إجازة في الرواية\n🕌 إجازة بالقراءة\n📚 سند الإجازة`,
    supportTitle: "📞 <b>الدعم والمساعدة</b>",
    supportBody: `تواصل مع الإدارة:\n\n📧 khdahd241@gmail.com\n📱 @aljezer_241`,
    contactTelegram: "💬 التواصل",
    adminNotAuthorized: "🚫 هذا الأمر للمشرفين فقط.",
    adminHelp: `🛠️ <b>أوامر المشرف</b>\n\n/add CODE MINUTES — إضافة دقائق\n/remove CODE MINUTES — خصم\n/info CODE — معلومات طالب\n/list — قائمة الطلاب\n/pending — طلبات معلقة\n/approve ID — اعتماد\n/reject ID — رفض\n/reply CODE MSG — رد\n/broadcast MSG — إشعار جماعي`,
    adminStudentNotFound: "❌ لا يوجد طالب بهذا الكود.",
    adminMinutesAdded: `✅ <b>تمت الإضافة</b>\n\n👤 {name}\n🔖 {code}\n⏱️ المضافة: {minutes}\n⏱️ الجديد: {total}`,
    adminMinutesRemoved: `✅ <b>تم الخصم</b>\n\n👤 {name}\n🔖 {code}\n⏱️ المخصوم: {minutes}\n⏱️ الجديد: {total}`,
    adminInvalidArgs: "⚠️ صيغة خاطئة. استخدم /help.",
    adminNoPending: "✅ لا توجد طلبات معلقة.",
    adminApproved: "✅ تم الاعتماد وإشعار الطالب.",
    adminRejected: "❌ تم الرفض وإشعار الطالب.",
    adminReplied: "✅ تم إرسال الرد.",
    adminBroadcastSent: "✅ تم الإرسال لـ {count} طالب.",
    adminInfo: `👤 <b>معلومات الطالب</b>\n\n🔖 {code}\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📱 {phone}\n📖 {level}\n\n📚 حفظ: {memorized_what}\n📍 {center}\n👨‍🏫 {teacher}\n\n⏱️ الرصيد: {minutes}\n📅 {reg_date}\n🆔 <code>{tid}</code>`,
    notifyNewRegistration: `🔔 <b>تسجيل جديد</b>\n\n👤 {name}\n🎂 {age} سنة\n⚥ {gender}\n📱 {phone}\n📖 {level}\n🔖 <code>{code}</code>\n🆔 <code>{tid}</code>\n\n📚 حفظ: {memorized_what}\n📅 {days} — {period}`,
    notifyNewReceipt: `🔔 <b>إيصال جديد</b>\n\n👤 {name}\n🔖 <code>{code}</code>\n💰 {price} ETB\n⏱️ {minutes}\n🆔 <code>{reqId}</code>\n\n/approve {reqId}\n/reject {reqId}`,
    notifyNewBooking: `🔔 <b>طلب حجز</b>\n\n👤 {name}\n🔖 {code}\n⏱️ {minutes}\n🕐 {period}`,
    notifyStudentMessage: `📩 <b>رسالة من طالب</b>\n\n👤 {name}\n🔖 {code}\n🆔 <code>{tid}</code>\n\n💬 {text}`
  },

  am: {
    chooseLang: "🌐 ቋንቋ ይምረጡ\n\nእንኳን ደህና መጡ።\nእባክዎ ቋንቋ ይምረጡ፦",
    langSaved: "✅ ቋንቋዎ ተቀምጧል፦ አማርኛ",
    anyTextWelcome: "🌿 እንኳን ደህና መጡ።\n\nአዝራሮቹን ይጠቀሙ 👇",
    errorMessage: "⚠️ ስህተት ተከስቷል። ቆይተው ይሞክሩ።",
    welcome: `ሰላም በእናንተ ላይ ይሁን 🌿\n\nእንኳን ደህና መጡ ወደ\n\n📖 <b>የኢማም አል-ጃዝሪ ቁርአን ማስተማሪያ</b>\n\nእንኳን ደህና መጡ {name} 🌹\n\nከታች ያለውን አገልግሎት ይምረጡ 👇`,
    homeWelcome: `📖 <b>የኢማም አል-ጃዝሪ ማስተማሪያ</b>\n\nእንኳን ደህና ተመለሱ 🌿\n\nአገልግሎት ይምረጡ፦`,
    btnPrograms: "📚 የትምህርት ፕሮግራሞች",
    btnTeachers: "👨‍🏫 ኡስታዞች",
    btnBalance: "⏱️ የደቂቃ ሂሳብ",
    btnBuy: "💳 ደቂቃ ግዢ",
    btnBooking: "📅 ቀጠሮ",
    btnAccount: "👤 መገለጫ",
    btnCertificates: "📜 ኢጃዞች",
    btnBooks: "📚 መጻሕፍት",
    btnAudio: "🎧 ድምጾች",
    btnSupport: "📞 ድጋፍ",
    btnHome: "🔙 ዋና ገጽ",
    btnBack: "🔙 ተመለስ",
    btnChangeLang: "🌐 ቋንቋ ቀይር",
    btnRegister: "📝 ይመዝገቡ",
    btnMySchedule: "📅 መርሐግብሬ",
    btnMyCode: "🔖 ኮዴ",
    regWelcome: `📝 <b>ምዝገባ</b>\n\nለመመዝገብ መረጃ ያስፈልጋል።\n\nዝግጁ ነዎት?`,
    regStartBtn: "✅ አዎ፣ እንጀምር",
    regCancelBtn: "❌ ሰርዝ",
    regAskName: "1️⃣ <b>ሙሉ ስምዎ?</b>\n\nጽሑፍ ይላኩ።",
    regAskAge: "2️⃣ <b>ዕድሜዎ?</b>\n\nቁጥር ብቻ።",
    regAskGender: "3️⃣ <b>ጾታ?</b>",
    regGenderMale: "👨 ወንድ",
    regGenderFemale: "👩 ሴት",
    regAskLevel: "4️⃣ <b>የንባብ ደረጃ?</b>",
    regLevel1: "🌱 ጀማሪ",
    regLevel2: "📖 መካከለኛ",
    regLevel3: "⭐ የላቀ",
    regLevel4: "🎓 ሀፊዝ",
    regAskPhone: "5️⃣ <b>ስልክ ቁጥር?</b>\n\n+251912345678",
    regAskMemorizedWhat: "6️⃣ <b>ምን አስታውሰዋል?</b>",
    regAskMemorizedWhere: "7️⃣ <b>የት አስታወሱ?</b>",
    regAskCenter: "8️⃣ <b>የማዕከሉ ስም?</b>",
    regAskTeacher: "9️⃣ <b>የኡስታዙ ስም?</b>",
    regAskDate: "🔟 <b>መቼ አስታወሱ?</b>",
    regAskSchedule: "📅 <b>ፕሮግራም ይምረጡ:</b>\n\n{details}",
    regScheduleMale: "ወንዶች: ማክሰኞ፣ ረቡዕ፣ ሐሙስ",
    regScheduleFemale: "ሴቶች: ቅዳሜ፣ እሑድ፣ ሰኞ",
    regAskPeriod: "⏰ <b>ጊዜ ይምረጡ:</b>",
    regPeriodMorning: "🌅 ጠዋት (9:00 - 11:00)",
    regPeriodAfternoon: "☀️ ከሰዓት (2:00 - 3:30)",
    regPeriodNight: "🌙 ማታ (9:00 - 11:00)",
    regConfirm: `📋 <b>ማረጋገጫ</b>\n\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📖 {level}\n📱 {phone}\n\n📚 <b>ማስታወሻ:</b>\n• {memorized_what}\n• {memorized_where}\n• {center}\n• {teacher}\n• {date}\n\n📅 {days}\n⏰ {period}\n\nያረጋግጡ?`,
    regConfirmBtn: "✅ አረጋግጥ",
    regEditBtn: "✏️ አርትዕ",
    regDone: `✅ <b>ተመዝግበዋል!</b>\n\n🔖 <b>ኮዴ:</b>\n<code>{code}</code>\n\n📅 {date}\n\n📌 ኮዴውን ያስቀምጡ።`,
    regCanceled: "❌ ተሰርዟል።",
    regAlreadyRegistered: `✅ አስቀድመው ተመዝግበዋል።\n\n🔖 <code>{code}</code>`,
    regInvalidAge: "⚠️ ቁጥር ብቻ (10-100)።",
    regInvalidPhone: "⚠️ ትክክለኛ ቁጥር ይላኩ።",
    programs: "📚 <b>ፕሮግራሞች</b>\n\nይምረጡ፦",
    progNorania: "📖 ኑራኒያ",
    progNazr: "🕌 ንባብ ማስተካከያ",
    progHifz: "📕 ማስታወስ",
    progHafs: "🎓 ሃፍስ እና ኢጃዛ",
    progSeven: "📚 ሰባቱ ቅርብ",
    progTen: "📚 አስሩ ቅርብ",
    noraniaTitle: "📖 <b>ኑራኒያ ፕሮግራም</b>",
    noraniaBody: `ለጀማሪዎች መሠረት።\n\n1️⃣ ፊደላት\n2️⃣ እንቅስቃሴዎች\n3️⃣ ተንዊን\n4️⃣ ማድ\n5️⃣ ሱኩን\n6️⃣ ሸዳ\n7️⃣ ላም\n8️⃣ ቃላት\n9️⃣ ልምምድ`,
    lessonsBtn: "📋 ትምህርቶች",
    bookSessionBtn: "📅 ቀጠሮ",
    backPrograms: "🔙 ፕሮግራሞች",
    lessonsTitle: "📖 <b>ኑራኒያ ትምህርቶች</b>\n\nይምረጡ፦",
    lessonTitle: "📖 <b>ትምህርት {n}</b>",
    lessonBody: `ከኡስታዝ ጋር ማጥናት ይችላሉ።\n\n🎧 ማዳመጥ\n📖 ማንበብ\n👨‍🏫 ማስተካከል`,
    bookWithTeacherBtn: "📅 ከኡስታዝ ጋር",
    backLessons: "🔙 ትምህርቶች",
    nazrTitle: "🕌 <b>ንባብ ማስተካከያ</b>",
    nazrBody: "የንባብ ማስተካከያ ፕሮግራም።",
    hifzTitle: "📕 <b>ማስታወስ</b>",
    hifzBody: "በደረጃ ማስታወስ።",
    hafsTitle: "🎓 <b>ሃፍስ እና ኢጃዛ</b>",
    hafsBody: "የተሟላ መስመር።",
    sevenTitle: "📚 <b>ሰባቱ ቅርብ</b>",
    sevenBody: "የሰባቱ ቅርብ ጥናት።",
    tenTitle: "📚 <b>አስሩ ቅርብ</b>",
    tenBody: "የአስሩ ቅርብ ፕሮግራም።",
    chooseTeacherBtn: "👨‍🏫 ኡስታዝ",
    teachers: "👨‍🏫 <b>ኡስታዞች</b>\n\nይምረጡ፦",
    teacherAbuZaid: "🟢 ኡስታዝ አቡ ዘይድ",
    salafiScholarsBtn: "📚 ሰላፊ ኡስታዞች",
    otherTeachers: "👨‍🏫 ሌሎች",
    teacherAbuZaidTitle: "👨‍🏫 <b>ኡስታዝ አቡ ዘይድ</b>",
    teacherAbuZaidBody: `🟢 ዝግጁ\n\n📖 ልዩ መስኮች፦\n• ንባብ\n• ተጅዊድ\n• ሃፍስ\n• ማስታወስ\n• ኢጃዛ\n\n📅 {schedule}`,
    backTeachers: "🔙 ኡስታዞች",
    salafiTitle: "📚 <b>ሰላፊ ኡስታዞች</b>\n\nይምረጡ፦",
    salafiBody: `📖 <b>{name}</b>\n\n{description}`,
    openChannelBtn: "▶️ ቻናል ክፈት",
    openPlaylistBtn: "📺 ዝርዝሮች",
    backSalafi: "🔙 ተመለስ",
    booksTitle: "📚 <b>መጻሕፍት</b>\n\nይምረጡ፦",
    downloadBtn: "⬇️ PDF አውርድ",
    watchExplanationBtn: "▶️ ማብራሪያ",
    backBooks: "🔙 መጻሕፍት",
    explanationTitle: "▶️ <b>{title}</b>\n\n({count} ክፍሎች)",
    audioTitle: "🎧 <b>ድምጾች</b>\n\nይምረጡ፦",
    audioBody: `🎙️ <b>{title}</b>`,
    watchNowBtn: "▶️ ተመልከት",
    backAudio: "🔙 ድምጾች",
    balanceTitle: "⏱️ <b>የደቂቃ ሂሳብ</b>",
    balanceBody: `👤 {name}\n\n⏱️ <b>{minutes} ደቂቃ</b>\n💰 <b>{value} ብር</b>\n\n💡 1 ደቂቃ = 5 ብር`,
    historyBtn: "📊 ታሪክ",
    historyTitle: "📊 <b>ታሪክ</b>",
    historyEmpty: "ምንም የለም።",
    backBalance: "🔙 ሂሳብ",
    buyTitle: "💳 <b>ደቂቃ ግዢ</b>",
    buyBody: "1 ደቂቃ = 5 ብር\n\nጥቅል ይምረጡ፦",
    confirmPackTitle: "💳 <b>ማረጋገጫ</b>",
    confirmPackBody: `⏱️ {minutes}\n💰 {price} ብር`,
    wantBuyBtn: "💰 ግዛ",
    backPackages: "🔙 ጥቅሎች",
    purchaseRequested: `✅ <b>ተመዝግቧል</b>\n\n📌 ደረሰኝ ይላኩ።`,
    sendReceiptNow: "📷 ደረሰኝ ላክ",
    receiptReceived: `✅ <b>ተቀብለናል</b>`,
    rechargeApproved: `🎉 <b>ተፈቅዷል</b>\n\n⏱️ {minutes}\n💰 {price}\n\n⏱️ አዲስ: {total}`,
    rechargeRejected: `❌ <b>ተ rejected</b>\n\n{reason}`,
    bookingTitle: "📅 <b>ቀጠሮ</b>",
    bookingBody: "ሂሳብ: {minutes}\n\nቆይታ ይምረጡ፦",
    noBalanceWarning: "⚠️ <b>ሂሳብ የለም።</b>",
    noBalanceBody: "ሂሳብ: {minutes}",
    min15: "15 ደቂቃ", min20: "20 ደቂቃ", min30: "30 ደቂቃ",
    min45: "45 ደቂቃ", min60: "60 ደቂቃ",
    notEnoughBalance: "❌ አይበቃም።",
    chooseSessionTime: "📅 <b>ሰዓት ይምረጡ</b>",
    chooseSessionTimeBody: "{minutes} ደቂቃ",
    morning: "🌅 ጠዋት", afternoon: "☀️ ከሰዓት", night: "🌙 ማታ",
    backBooking: "🔙 ቀጠሮ",
    bookingRequestTitle: "📅 <b>የቀጠሮ ጥያቄ</b>",
    bookingRequestBody: `⏱️ {minutes}\n🕐 {period}`,
    sendBookingBtn: "✅ ላክ",
    cancelBtn: "❌ ሰርዝ",
    bookingConfirmedTitle: "✅ <b>ተልኳል</b>",
    bookingConfirmedBody: `⏱️ {minutes}\n⏱️ ቀሪ: {remaining}`,
    myBalanceBtn: "⏱️ ሂሳቤ",
    notEnoughShort: "❌ አይበቃም።",
    accountTitle: "👤 <b>መገለጫ</b>",
    accountBody: `{name}\n🔖 <code>{code}</code>\n🎂 {age}\n⚥ {gender}\n📖 {level}\n📱 {phone}\n\n⏱️ {minutes}\n📚 {program}\n📅 {days}\n⏰ {period}\n\n📌 {reg_date}`,
    notSet: "የለም",
    noProgram: "አልተመረጠም",
    chooseProgramBtn: "📚 ፕሮግራም",
    historyShortBtn: "📊 ታሪክ",
    notRegistered: "⚠️ አልተመዘገቡም።",
    certificatesTitle: "📜 <b>ኢጃዞች</b>",
    certificatesBody: `🎓 ሰርተፊኬት\n📜 ማስታወስ\n📖 ኢጃዛ\n🕌 ንባብ`,
    supportTitle: "📞 <b>ድጋፍ</b>",
    supportBody: `📧 khdahd241@gmail.com\n📱 @aljezer_241`,
    contactTelegram: "💬 ያግኙን",
    adminNotAuthorized: "🚫 ለአስተዳዳሪ ብቻ።",
    adminHelp: `/add CODE MINUTES\n/remove CODE MINUTES\n/info CODE\n/list\n/pending\n/approve ID\n/reject ID\n/reply CODE MSG\n/broadcast MSG`,
    adminStudentNotFound: "❌ አልተገኘም።",
    adminMinutesAdded: `✅ {name}\n⏱️ {minutes}\n⏱️ አዲስ: {total}`,
    adminMinutesRemoved: `✅ {name}\n⏱️ {minutes}\n⏱️ አዲስ: {total}`,
    adminInvalidArgs: "⚠️ የተሳሳተ ትዕዛዝ።",
    adminNoPending: "✅ ምንም የለም።",
    adminApproved: "✅ ተፈቅዷል።",
    adminRejected: "❌ ተ rejected።",
    adminReplied: "✅ ተልኳል።",
    adminBroadcastSent: "✅ ለ {count} ተልኳል።",
    adminInfo: `🔖 {code}\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📱 {phone}\n📖 {level}\n⏱️ {minutes}\n🆔 <code>{tid}</code>`,
    notifyNewRegistration: `🔔 <b>አዲስ ምዝገባ</b>\n\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📱 {phone}\n🔖 <code>{code}</code>\n🆔 <code>{tid}</code>`,
    notifyNewReceipt: `🔔 <b>አዲስ ደረሰኝ</b>\n\n👤 {name}\n🔖 <code>{code}</code>\n💰 {price}\n🆔 <code>{reqId}</code>\n\n/approve {reqId}`,
    notifyNewBooking: `🔔 <b>ቀጠሮ</b>\n\n👤 {name}\n🔖 {code}\n⏱️ {minutes}`,
    notifyStudentMessage: `📩 <b>መልዕክት</b>\n\n👤 {name}\n🔖 {code}\n💬 {text}`
  },

  en: {
    chooseLang: "🌐 Choose your language\n\nWelcome to Imam Al-Jazari Academy.\nPlease choose:",
    langSaved: "✅ Your language: English",
    anyTextWelcome: "🌿 Welcome.\n\nUse the menu 👇",
    errorMessage: "⚠️ Temporary error. Try again.",
    welcome: `Peace be upon you 🌿\n\nWelcome to\n\n📖 <b>Imam Al-Jazari Quran Academy</b>\n\nWelcome {name} 🌹\n\nChoose a service below 👇`,
    homeWelcome: `📖 <b>Imam Al-Jazari Academy</b>\n\nWelcome back 🌿\n\nChoose:`,
    btnPrograms: "📚 Programs",
    btnTeachers: "👨‍🏫 Teachers",
    btnBalance: "⏱️ Balance",
    btnBuy: "💳 Buy Minutes",
    btnBooking: "📅 Book Session",
    btnAccount: "👤 Account",
    btnCertificates: "📜 Certificates",
    btnBooks: "📚 Books",
    btnAudio: "🎧 Audio",
    btnSupport: "📞 Support",
    btnHome: "🔙 Home",
    btnBack: "🔙 Back",
    btnChangeLang: "🌐 Change Language",
    btnRegister: "📝 Register",
    btnMySchedule: "📅 My Schedule",
    btnMyCode: "🔖 My Code",
    regWelcome: `📝 <b>Registration</b>\n\nWe need some info.\n\nReady?`,
    regStartBtn: "✅ Yes, start",
    regCancelBtn: "❌ Cancel",
    regAskName: "1️⃣ <b>Full name?</b>\n\nSend text.",
    regAskAge: "2️⃣ <b>Age?</b>\n\nNumbers only.",
    regAskGender: "3️⃣ <b>Gender?</b>",
    regGenderMale: "👨 Male",
    regGenderFemale: "👩 Female",
    regAskLevel: "4️⃣ <b>Reading level?</b>",
    regLevel1: "🌱 Beginner",
    regLevel2: "📖 Intermediate",
    regLevel3: "⭐ Advanced",
    regLevel4: "🎓 Hafiz",
    regAskPhone: "5️⃣ <b>Phone?</b>\n\n+251912345678",
    regAskMemorizedWhat: "6️⃣ <b>What have you memorized?</b>",
    regAskMemorizedWhere: "7️⃣ <b>Where did you memorize?</b>",
    regAskCenter: "8️⃣ <b>Center name?</b>",
    regAskTeacher: "9️⃣ <b>Teacher name?</b>",
    regAskDate: "🔟 <b>When?</b>",
    regAskSchedule: "📅 <b>Choose program:</b>\n\n{details}",
    regScheduleMale: "Men: Tue, Wed, Thu",
    regScheduleFemale: "Women: Sat, Sun, Mon",
    regAskPeriod: "⏰ <b>Period:</b>",
    regPeriodMorning: "🌅 Morning (9-11)",
    regPeriodAfternoon: "☀️ Afternoon (2-3:30)",
    regPeriodNight: "🌙 Evening (9-11)",
    regConfirm: `📋 <b>Confirm</b>\n\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📖 {level}\n📱 {phone}\n\n📚 {memorized_what}\n📅 {days} — {period}\n\nOK?`,
    regConfirmBtn: "✅ Confirm",
    regEditBtn: "✏️ Edit",
    regDone: `✅ <b>Registered!</b>\n\n🔖 <code>{code}</code>\n\n📅 {date}\n\n📌 Keep this code.`,
    regCanceled: "❌ Canceled.",
    regAlreadyRegistered: `✅ Already registered.\n\n🔖 <code>{code}</code>`,
    regInvalidAge: "⚠️ Numbers only (10-100).",
    regInvalidPhone: "⚠️ Invalid phone.",
    programs: "📚 <b>Programs</b>",
    progNorania: "📖 Nuraniyah",
    progNazr: "🕌 Recitation",
    progHifz: "📕 Memorization",
    progHafs: "🎓 Hafs & Ijazah",
    progSeven: "📚 Seven Qira'at",
    progTen: "📚 Ten Qira'at",
    noraniaTitle: "📖 <b>Nuraniyah</b>",
    noraniaBody: `Beginners program:\n1️⃣ Letters\n2️⃣ Vowels\n3️⃣ Tanween\n4️⃣ Madd\n5️⃣ Sukoon\n6️⃣ Shaddah\n7️⃣ Lam\n8️⃣ Words\n9️⃣ Practice`,
    lessonsBtn: "📋 Lessons",
    bookSessionBtn: "📅 Book",
    backPrograms: "🔙 Programs",
    lessonsTitle: "📖 <b>Lessons</b>",
    lessonTitle: "📖 <b>Lesson {n}</b>",
    lessonBody: `Study with a teacher.\n\n🎧 Listen\n📖 Read\n👨‍🏫 Correct`,
    bookWithTeacherBtn: "📅 Book",
    backLessons: "🔙 Lessons",
    nazrTitle: "🕌 <b>Recitation</b>",
    nazrBody: "Correction program.",
    hifzTitle: "📕 <b>Memorization</b>",
    hifzBody: "Gradual memorization.",
    hafsTitle: "🎓 <b>Hafs & Ijazah</b>",
    hafsBody: "Full track.",
    sevenTitle: "📚 <b>Seven Qira'at</b>",
    sevenBody: "Seven Qira'at study.",
    tenTitle: "📚 <b>Ten Qira'at</b>",
    tenBody: "Ten Qira'at program.",
    chooseTeacherBtn: "👨‍🏫 Choose",
    teachers: "👨‍🏫 <b>Teachers</b>",
    teacherAbuZaid: "🟢 Sheikh Abu Zaid",
    salafiScholarsBtn: "📚 Salafi Scholars",
    otherTeachers: "👨‍🏫 Others",
    teacherAbuZaidTitle: "👨‍🏫 <b>Sheikh Abu Zaid</b>",
    teacherAbuZaidBody: `🟢 Available\n\n📖 Specialties:\n• Recitation\n• Tajweed\n• Hafs\n• Memorization\n• Ijazah\n\n📅 {schedule}`,
    backTeachers: "🔙 Teachers",
    salafiTitle: "📚 <b>Salafi Scholars</b>",
    salafiBody: `📖 <b>{name}</b>\n\n{description}`,
    openChannelBtn: "▶️ Open Channel",
    openPlaylistBtn: "📺 Playlists",
    backSalafi: "🔙 Back",
    booksTitle: "📚 <b>Books</b>",
    downloadBtn: "⬇️ Download PDF",
    watchExplanationBtn: "▶️ Watch",
    backBooks: "🔙 Books",
    explanationTitle: "▶️ <b>{title}</b>\n\n({count} videos)",
    audioTitle: "🎧 <b>Audio</b>",
    audioBody: `🎙️ <b>{title}</b>`,
    watchNowBtn: "▶️ Watch",
    backAudio: "🔙 Audio",
    balanceTitle: "⏱️ <b>Balance</b>",
    balanceBody: `👤 {name}\n\n⏱️ <b>{minutes} min</b>\n💰 <b>{value} ETB</b>\n\n💡 1 min = 5 ETB`,
    historyBtn: "📊 History",
    historyTitle: "📊 <b>History</b>",
    historyEmpty: "No data.",
    backBalance: "🔙 Balance",
    buyTitle: "💳 <b>Buy</b>",
    buyBody: "1 min = 5 ETB\n\nChoose:",
    confirmPackTitle: "💳 <b>Confirm</b>",
    confirmPackBody: `⏱️ {minutes}\n💰 {price} ETB`,
    wantBuyBtn: "💰 Buy",
    backPackages: "🔙 Packages",
    purchaseRequested: `✅ <b>Recorded</b>\n\n📌 Send receipt.`,
    sendReceiptNow: "📷 Send receipt",
    receiptReceived: `✅ <b>Received</b>`,
    rechargeApproved: `🎉 <b>Approved</b>\n\n⏱️ {minutes}\n💰 {price}\n\n⏱️ New: {total}`,
    rechargeRejected: `❌ <b>Rejected</b>\n\n{reason}`,
    bookingTitle: "📅 <b>Book</b>",
    bookingBody: "Balance: {minutes}\n\nChoose duration:",
    noBalanceWarning: "⚠️ <b>No balance.</b>",
    noBalanceBody: "Balance: {minutes}",
    min15: "15 min", min20: "20 min", min30: "30 min",
    min45: "45 min", min60: "60 min",
    notEnoughBalance: "❌ Not enough.",
    chooseSessionTime: "📅 <b>Choose time</b>",
    chooseSessionTimeBody: "{minutes} min",
    morning: "🌅 Morning", afternoon: "☀️ Afternoon", night: "🌙 Evening",
    backBooking: "🔙 Booking",
    bookingRequestTitle: "📅 <b>Booking</b>",
    bookingRequestBody: `⏱️ {minutes}\n🕐 {period}`,
    sendBookingBtn: "✅ Send",
    cancelBtn: "❌ Cancel",
    bookingConfirmedTitle: "✅ <b>Sent</b>",
    bookingConfirmedBody: `⏱️ {minutes}\n⏱️ Remaining: {remaining}`,
    myBalanceBtn: "⏱️ Balance",
    notEnoughShort: "❌ Not enough.",
    accountTitle: "👤 <b>Account</b>",
    accountBody: `{name}\n🔖 <code>{code}</code>\n🎂 {age}\n⚥ {gender}\n📖 {level}\n📱 {phone}\n\n⏱️ {minutes}\n📚 {program}\n📅 {days}\n⏰ {period}\n\n📌 {reg_date}`,
    notSet: "Not set",
    noProgram: "Not selected",
    chooseProgramBtn: "📚 Program",
    historyShortBtn: "📊 History",
    notRegistered: "⚠️ Not registered.",
    certificatesTitle: "📜 <b>Certificates</b>",
    certificatesBody: `🎓 Completion\n📜 Memorization\n📖 Ijazah\n🕌 Recitation`,
    supportTitle: "📞 <b>Support</b>",
    supportBody: `📧 khdahd241@gmail.com\n📱 @aljezer_241`,
    contactTelegram: "💬 Contact",
    adminNotAuthorized: "🚫 Admins only.",
    adminHelp: `/add CODE MINUTES\n/remove CODE MINUTES\n/info CODE\n/list\n/pending\n/approve ID\n/reject ID\n/reply CODE MSG\n/broadcast MSG`,
    adminStudentNotFound: "❌ Not found.",
    adminMinutesAdded: `✅ {name}\n⏱️ {minutes}\n⏱️ New: {total}`,
    adminMinutesRemoved: `✅ {name}\n⏱️ {minutes}\n⏱️ New: {total}`,
    adminInvalidArgs: "⚠️ Invalid command.",
    adminNoPending: "✅ No pending.",
    adminApproved: "✅ Approved.",
    adminRejected: "❌ Rejected.",
    adminReplied: "✅ Sent.",
    adminBroadcastSent: "✅ Sent to {count}.",
    adminInfo: `🔖 {code}\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📱 {phone}\n📖 {level}\n⏱️ {minutes}\n🆔 <code>{tid}</code>`,
    notifyNewRegistration: `🔔 <b>New registration</b>\n\n👤 {name}\n🎂 {age}\n⚥ {gender}\n📱 {phone}\n🔖 <code>{code}</code>\n🆔 <code>{tid}</code>`,
    notifyNewReceipt: `🔔 <b>New receipt</b>\n\n👤 {name}\n🔖 <code>{code}</code>\n💰 {price}\n🆔 <code>{reqId}</code>\n\n/approve {reqId}`,
    notifyNewBooking: `🔔 <b>Booking</b>\n\n👤 {name}\n🔖 {code}\n⏱️ {minutes}`,
    notifyStudentMessage: `📩 <b>Message</b>\n\n👤 {name}\n🔖 {code}\n💬 {text}`
  }
};
